# Generated by Django 4.0.4 on 2022-05-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_alter_userregistration_regno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='contactNo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
